### ISSUE TITLE
Can't run a printf command

### ISSUE THREAD

**Issue by ilium007** [lingfish/proxmox-grapple#2]
Not sure what is happening but when I run the following it errors.

```
root@pve01:~# cat /etc/proxmox_grapple.yml
production:
  job-start:
    script:
      - 'printf "$(date) PVE hook script start pve01 - $(pveversion)\n" | tee /mnt/ext_usb_01/pve01.log'
```

But works from command line:

`root@pve01:~# printf "$(date) PVE hook script start pve01 - $(pveversion)\n" | tee /mnt/ext_usb_01/pve01.log`

Error in the Proxmox backup console:

```
INFO: HOOK: /root/.local/bin/proxmox-grapple job-start
INFO: HOOK-ENV: vmtype=None; dumpdir=/mnt/ext_usb_01/dump; storeid=ext_usb_01; hostname=None; tarfile=None; logfile=None
INFO:     Running: printf "$(date) PVE hook script start pve01 - $(pveversion)\n" | tee /mnt/ext_usb_01/pve01.log
INFO:     "$(date)printf: warning: ignoring excess arguments, starting with 'PVE'
```

**Comment by lingfish** [comment]
So this one makes sense -- just like `vzdump`, grapple basically does a Python `execvpe`... exec's whatever you configure on the `script` lines.  The key here is that it **does not** run a shell around your commands, so shell-specific things like pipes and command substitution/variable expansion obviously won't work.

My assumption had been that if a user wanted that, they'd configure grapple with something along the lines of `bash -c "confusing_mess_with_single_and_double_quotes and_escaping"`

I could look into a config option to turn on Popen's `shell=True`, but would be low on the list.

**Comment by ilium007** [comment]
All good. I'll have to find a different solution.

**Comment by lingfish** [comment]
You could put that/those lines into a shell script, with a shebang at the top, or yeah, wrap it in a `sh/bash -c` line.

**Comment by ilium007** [comment]
That's were I started, a shell script with a shebang!

```
#!/bin/bash

PVE_NODE="$(hostname)"
LOG_FILE="/mnt/ext_usb_01/$PVE_NODE.log"

if [ "$1" == "job-start" ]; then
  printf "$(date) PVE hook script start ($PVE_NODE) - $(pveversion)\n" | tee $LOG_FILE
fi

if [ "$1" == "job-end" ]; then
  /usr/local/bin/autorestic -c /root/.autorestic.yml --restic-bin /usr/local/bin/restic backup --verbose --all 2>&1 | tee -a $LOG_FILE
fi
```

**Comment by lingfish** [comment]
Well, I've now implemented the `shell` option, hopefully this helps!

https://github.com/lingfish/proxmox-grapple/releases/tag/1.5.5

**Comment by ilium007** [comment]
I will give it a go. I got autorestic working in the standard shell script by including PATH=$PATH before calling autorestic (don't ask me why it works)

```
#!/bin/bash

PVE_NODE="$(hostname)"
LOG_FILE="/mnt/ext_usb_01/$PVE_NODE.log"
PATH=$PATH

if [ "$1" == "job-start" ]; then
  printf "$(date) PVE hook script start ($PVE_NODE) - $(pveversion)\n" | tee $LOG_FILE
fi

if [ "$1" == "job-end" ]; then
  /usr/local/bin/autorestic -c /root/.autorestic.yml --restic-bin /usr/local/bin/restic backup --verbose --all 2>&1 | tee -a $LOG_FILE
fi
```
